[workspace]
resolver = "2"
members = ["authz", "authz_run", "jwt"]

[workspace.dependencies]
authz = { path = "authz" }
jwt = { path = "jwt" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.63"
