[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.0"
base64 = "0.22.1"
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
